name: Combined Stats Generator

on:
  schedule:
    - cron: "0 */12 * * *"  # Runs every 12 hours
  workflow_dispatch:  # Allows manual trigger

jobs:
  monkeytype-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "latest"

      # Generate basic stats
      - name: Generate Basic Monkeytype Stats
        uses: monkeytype-hub/monkeytype-readme@v1.0.0
        with:
          username: akkaraponph
          themes: nord_light
          target-branch: monkey-type
          github-token: ${{ secrets.GH_TOKEN }}

      # Generate stats with Leaderboards
      - name: Generate Monkeytype Stats with Leaderboards
        uses: monkeytype-hub/monkeytype-readme@v1.0.0
        with:
          username: akkaraponph
          themes: nord_light
          target-branch: monkey-type
          github-token: ${{ secrets.GH_TOKEN }}
          leaderboard: true

      # Generate stats with Personal Bests
      - name: Generate Monkeytype Stats with Personal Bests
        uses: monkeytype-hub/monkeytype-readme@v1.0.0
        with:
          username: akkaraponph
          themes: nord_light
          target-branch: monkey-type
          github-token: ${{ secrets.GH_TOKEN }}
          personal-bests: true

      # Generate stats with both Leaderboards and Personal Bests
      - name: Generate Monkeytype Stats with Leaderboards and Personal Bests
        uses: monkeytype-hub/monkeytype-readme@v1.0.0
        with:
          username: akkaraponph
          themes: nord_light
          target-branch: monkey-type
          github-token: ${{ secrets.GH_TOKEN }}
          leaderboard: true
          personal-bests: true

  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
    
      - name: Generate the snake files
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
        env:
           GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Push to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  update-waka-stats:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: guilyx/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SECTION_NAME: "waka-simple"
          COMMIT_MESSAGE: "build: updated simple waka stats section"
          BLOCKS: "⣀⣄⣤⣦⣶⣷⣿"
          TIME_RANGE: all_time
          SHOW_TIME: true
          SHOW_MASKED_TIME: true
          SHOW_TITLE: true
          SHOW_OS: "False"
          SHOW_PROJECTS: "True"
          SHOW_UPDATED_DATE: "True"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_EDITORS: "False"
          SHOW_LANGUAGE: "True"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_LINES_OF_CODE: "True"
          SHOW_COMMIT: "True"
          SHOW_LOC_CHART: "False"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_SHORT_INFO: "False"